### ISSUE TITLE
add a Readme file

### ISSUE THREAD

**Issue by Suman-Banakar** [Suman-Banakar/Android#2]

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**Following Worker has started work on the bounty. .**

Below user(s) claimed they can complete the work within defined time period.

Please review their action plans below:

**1) <a href='https://sandbox.app.gitcommits.com/profile/contrib1'>contrib1</a> started work on the bounty on 26 Aug.**

**Message:** starting work



<hr>

**This issue has a bounty of $50.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://sandbox.app.gitcommits.com/issue/add-a-readme-file).
- Questions? Checkout [GitCommits Help](https://sandbox.app.gitcommits.com/help) or the [GitCommits Slack](https://sandbox.app.gitcommits.com/slack)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://sandbox.app.gitcommits.com/explorer)

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/contrib1'>contrib1</a>, has started work on the bounty.**
<hr />

**Message:** starting work


<a href='https://sandbox.app.gitcommits.com/issue/add-a-readme-file'>Click Here to view more</a> on GitCommits Bounty detail page.
